- Взаимосвязь величин. Параметрические и непараметрические показатели корреляции. Корреляционный анализ.

1) Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):

zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].

Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy

Полученные значения должны быть равны.

Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков, а затем с использованием функций из библиотек numpy и pandas.

In [1]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
print(zp)
print(ks)

[ 35  45 190 200  40  70  54 150 120 110]
[401 574 874 919 459 739 653 902 746 832]


Ковариация двух величин, вычисленная с помощью элементраных действий:

In [2]:
cov = np.mean(zp * ks) - np.mean(zp) * np.mean(ks)
cov

9157.839999999997

Ковариация с помощью функции cov из numpy

In [3]:
np.cov(zp, ks, ddof=0)

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

Коэффициент корреляции Пирсона рассчитываем по формуле:

$$r_{XY} = \frac{cov_{XY}}{\sigma_{X}\sigma_{Y}}$$

Для этого находим стандратное отклонение sigma двух генеральных совокупностей:

In [4]:
sigma_zp =  (np.sqrt(((zp - zp.sum() / len(zp))**2).sum() / len(zp)))
sigma_ks =  (np.sqrt(((ks - ks.sum() / len(ks))**2).sum() / len(ks)))
print(sigma_zp)
print(sigma_ks)

59.115480206118605
174.55340157098058


Проверяем правильность вычислений

In [5]:
sigma_zp_= zp.std(ddof=0)
sigma_ks_ = ks.std(ddof=0)
print(sigma_zp_)
print(sigma_ks_)

59.115480206118605
174.55340157098058


Подставляем полученные значения в формулу и вычисляем коэффициент корреляции Пирсона:

In [6]:
r = cov / (sigma_zp * sigma_ks)
r

0.8874900920739158

Найдём коэффициент корреляции Пирсона с помощью функции NumPy и Pandas.

In [7]:
r = np.corrcoef(zp, ks)
r

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

Коэффициенты корреляции совпадают.

2) Измерены значения IQ выборки студентов, обучающихся в местных технических вузах: 131, 125, 115, 122, 131, 115, 107, 99, 125, 111.

Известно, что в генеральной совокупности IQ распределен нормально.

Найдите доверительный интервал для математического ожидания с надежностью 0.95.

Рассчитаем предельное отклонение от средней арифметической по следующей формуле:

$$T_{1,2} = \overline{X} \pm \frac{s_0}{\sqrt{n}} \cdot c_{\gamma}$$

где $T_1$, $T_2$ — нижняя и верхняя границы доверительного интервала,

$\overline{X}$  — выборочное среднее арифметическое, $s_0$ — среднее квадратичное отклонение по выборке (несмещенное),

$n$ — размер выборки,

$\gamma$ — доверительная вероятность,

$c_{\gamma} = Ф^{-1} \frac{(1 + \gamma)}{2}$ — обратное значение функции стандартного нормального распределения.

Итоговая формула: $$\left(\overline{x} - Z_{\frac{a}{2}} \cdot \frac{\sigma}{\sqrt{n}} , \overline{x} + Z_{\frac{a}{2}} \cdot \frac{\sigma}{\sqrt{n}}\right)$$

In [8]:
iq = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
n = len(iq)
t = 2.262
iq_mean = iq.sum() / len(iq)
print(iq_mean)
sigma =  (np.sqrt(((iq - iq.sum() / n)**2).sum() / (n - 1)))
print(sigma)
T1 = iq_mean - t * sigma / (n ** 0.5)
T2 = iq_mean + t * sigma / (n ** 0.5)
print(f'Доверительный интервал имеет границы ({T1}, {T2})')

118.1
10.54566788359614
Доверительный интервал имеет границы (110.55660776308164, 125.64339223691834)


3) Известно, что рост футболистов в сборной распределен нормально с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27, среднее выборочное составляет 174.2. Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [9]:
D = 25
n = 27
X_ = 174.2
alpha = 0.05
t = 1.96

sigma =  np.sqrt(D)
T1 = X_ - t * sigma / (n ** 0.5)
T2 = X_ + t * sigma / (n ** 0.5)
print(f'Доверительный интервал имеет границы ({T1}, {T2})')

Доверительный интервал имеет границы (172.31398912064722, 176.08601087935276)


4.Выберите тему для проектной работы по курсу Теории вероятностей и математической статистики и напишите ее в комментарии к Практическому заданию. (ПРОЕКТ ДОБРОВОЛЬНЫЙ)

Описание курсового проекта по предмету Теория вероятностей и математическая статистика

Во второй половине курса студентам даётся проект с темой на выбор. Студентам предлагается общее направление для проекта - исследовать данные с imdb. Для этих данных можно сделать EDA (Exploratory Data Analysis – разведочный анализ данных) либо проверить предложенную самим студентом статистическую гипотезу. При наличии опыта работы с данными и статистикой некоторые студенты также могут взять другую тему - например, исследовать курс биткойна.

В качестве данных студенты могут брать датасеты с информацией с сайта imdb (либо с Kaggle, либо откуда-то из Интернета, эти данные нужно искать самим). Также есть возможность взять любые другие данные, если выбрана другая тема. Работы выполняются с использованием любых методов из вебинаров и методичек по предмету Теория вероятностей и математическая статистика. Это может быть постановка и проверка статистических гипотез, EDA, дисперсионный анализ и т.д.

Готовый проект должен быть выложен на github в аккаунте студента в виде файла с расширением ipynb (Jupyter Notebook), ссылка на проект прикладывается в раздел Задание. Срок выполнения задания - неделя после 8-го вебинара. Начинать можно после 6-го вебинара, после того, как преподаватель одобрит тему (студент указывает тему работы в Задание к вебинару 6).

Ссылка на проект должна быть добавлена студентом к Заданию вебинара 8.

Примеры постановки темы проекта:

Проверить гипотезу: Комедийные фильмы, снятые до 1990 года, в среднем имеют более высокую оценку, чем комедийные фильмы, снятые позже.
Статистическое сопоставление цены биткоина с курсами фиатных активов (USD,EUR,RUR), ценами на нефть, драг металлы или с ценами других криптовалют по отношению к биткойну.
Также студент может до выполнения работы поставить широкий круг задач для проекта и уже в процессе выполнения оставить только то, что вошло в проект.

Пример:

"В проектной работе хотела бы сделать анализ по Странам по данным imbd.com.
По странам рассчитать основные статистические показатели: Мода, медиана, квартили, дисперсию.
Проверить, работает ли нормальное распределение и Паретто.
Проверить есть ли зависимость бюджетов, рейтингов, жанров от страны выпуска фильмов.
Посмотреть поведение стран во времени.
В идеале, хотела бы сделать прогноз на 2020 год: какие страны с какой вероятностью выпустят определенное количество фильмов с определенным бюджетом определенного жанра."