# Урок 3. Матрицы и матричные операции. Часть 1

Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

_Решение_

а) произведение не определено

б) произведение определено. Размерность произведения 2 х 3

в) произведение определено. Размерность произведения 8 х 8

г) произведение определено. Размерность произведения 4 х 4

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

_Решение_

Сумма матриц:

$$ A + B =
\begin{pmatrix}
1 & -2\\ 
3 & 0\\
\end{pmatrix}
+
\begin{pmatrix}
4 & -1\\ 
0 & 5\\
\end{pmatrix}
=
\begin{pmatrix}
5 & -3\\ 
3 & 5\\
\end{pmatrix}$$

Произведение:


$$
A \cdot B =
\begin{pmatrix}
1 & -2\\ 
3 & 0\\
\end{pmatrix} 
\cdot
\begin{pmatrix}
4 & -1\\ 
0 & 5\\
\end{pmatrix} = 
\begin{pmatrix}
1\cdot 4 + (-2)\cdot 0 & 1\cdot (-1) + (-2)\cdot 5\\ 
3\cdot 4 + 0\cdot 0 & 3\cdot (-1) + 0\cdot 5\\
\end{pmatrix} = 
\begin{pmatrix}
4 & -11\\ 
12 & -3\\
\end{pmatrix}
$$

_Решение_ с использованием NumPy

In [1]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')

Матрица A
[[ 1 -2]
 [ 3  0]]
Матрица B
[[ 4 -1]
 [ 0  5]]
Матрица AB
[[  4 -11]
 [ 12  -3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

_Решение_

$$
3 \cdot A -2 \cdot B + 4 \cdot C =
3 \cdot
\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix} 
-2\cdot
\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}
+4\cdot
\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}
=
\begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix} 
-
\begin{pmatrix}
0 & 10\\ 
4 & -2
\end{pmatrix}
+
\begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix}
=
\begin{pmatrix}
3 - 0 + 8 & 21 - 10 - 16 \\ 
9 - 4 + 4 & -18 - (-2) + 4
\end{pmatrix} = 
\begin{pmatrix}
11 & -5\\ 
9 & -10
\end{pmatrix}
$$

_Решение_ с использованием NumPy

In [2]:
A = np.array([[1, 7], [3, 6]])
B = np.array([[0, 5], [2, -1]])
С = np.array([[2, -4], [1, 1]])

print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица С\n{С}')
print(f'Матрица 3𝐴−2𝐵+4𝐶\n{3 * A - 2 * B + 4 * С}')

Матрица A
[[1 7]
 [3 6]]
Матрица B
[[ 0  5]
 [ 2 -1]]
Матрица С
[[ 2 -4]
 [ 1  1]]
Матрица 3𝐴−2𝐵+4𝐶
[[11 -5]
 [ 9 24]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$$ AA^T = 
\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3\\
\end{pmatrix}
\cdot
\begin{pmatrix}
4 &  5 & 2\\ 
1 & -2 & 3\\
\end{pmatrix}
=
\begin{pmatrix}
4 \cdot 4 + 1 \cdot 1 & 4 \cdot 5 + 1 \cdot (-2) & 4 \cdot 2 + 1 \cdot 3 \\
5 \cdot 4 + (-2) \cdot 1 & 5 \cdot 5 + (-2) \cdot (-2) & 5 \cdot 2 + (-2) \cdot 3 \\
2 \cdot 4 + 3 \cdot 1 & 2 \cdot 5 + 3 \cdot (-2) & 2 \cdot 2 + 3 \cdot 3\\
\end{pmatrix}
=
\begin{pmatrix}
17 &  18 & 11\\ 
18 & 29 & 4\\
11 & 4 & 13\\
\end{pmatrix} $$


$$ A^{T}A = 
\begin{pmatrix}
4 &  5 & 2\\ 
1 & -2 & 3\\
\end{pmatrix}
\cdot
\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3\\
\end{pmatrix}
=
\begin{pmatrix}
4 \cdot 4 + 5 \cdot 5 + 2 \cdot 2 & 4 \cdot 1 + 5 \cdot (-2) + 2 \cdot 3 \\
1 \cdot 4 + (-2) \cdot 5 + 3 \cdot 2 & 1 \cdot 1 (-2) \cdot (-2) + 3 \cdot 3 \\
\end{pmatrix}
=
\begin{pmatrix}
45 &  0\\ 
0 & 14\\
\end{pmatrix} $$

In [3]:
A = np.array([[4, 1], [5, -2], [2, 3]])

print(f'Матрица A\n{A}')
print(f'Транспонированная матрица А\n{A.T}')
print(f'произведение матрицы А и транспонированной матрицы\n{np.dot(A, A.T)}')
print(f'произведение матрицы А и транспонированной матрицы\n{np.dot(A.T, A)}')

Матрица A
[[ 4  1]
 [ 5 -2]
 [ 2  3]]
Транспонированная матрица А
[[ 4  5  2]
 [ 1 -2  3]]
произведение матрицы А и транспонированной матрицы
[[17 18 11]
 [18 29  4]
 [11  4 13]]
произведение матрицы А и транспонированной матрицы
[[45  0]
 [ 0 14]]


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

# Урок 4. Матрицы и матричные операции. Часть 2

Все задания рекомендуется выполнять вручную, затем проверяя полученные результаты с использованием Numpy.

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx\\
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9\\
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9\\
\end{vmatrix}.$$

_Решение_

a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx\\
\end{vmatrix}
= sin^2x + cos^2x = 1
$$

б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9\\
\end{vmatrix}
=
4 \cdot 5 \cdot 9 + 2 \cdot 1 \cdot 0 + 0 \cdot 0 \cdot 3 - 3 \cdot 5 \cdot0 - 2 \cdot 0 \cdot 9 - 1 \cdot 0 \cdot 4 = 180 + 0 + 0 - 0 - 0 - 0 = 180
$$
    
в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9\\
\end{vmatrix}
= 1 \cdot 5 \cdot 9 + 2 \cdot 6 \cdot 7 + 4 \cdot 8 \cdot 3 - 3 \cdot 5 \cdot 7 - 6 \cdot 8 \cdot 1 - 2 \cdot 4 \cdot 9 = 45 + 84 + 96 - 105 - 48 - 72 = 0
$$

In [4]:
a = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')
print(f'Матрица:\n{b}')
print(f'Определитель:\n{np.linalg.det(b):.0f}')

Матрица:
[[4 2 3]
 [0 5 1]
 [0 0 9]]
Определитель:
180
Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель:
-0


__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

__Решение__

   а) $det(A^{2}) = 4^2 = 16 $  т.к. для двух квадратных матриц одинакового размера $det(AB)=detA\cdot detB$
    
   б) $det(A^{T}) = 4 $ т.к. определитель транспонированной матрицы равен определителю исходной.
    
   в) $det(2A) = 2 \cdot 4 = 8 $

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13\\
\end{pmatrix}$$
   
вырожденная.

_Доказательство_

$$\begin{vmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13\\
\end{vmatrix}
= -2 \cdot -14 \cdot 13 + 7 \cdot 6 \cdot -3 + 4 \cdot 7 \cdot -3 - -3 \cdot -14 \cdot -3 - 6 \cdot 7 \cdot -2 - 7 \cdot 4 \cdot 13 = 364 - 126 - 84 + 126 + 84 - 364 = 0
$$

Определитель равен нулю, следовательно матрица является вырожденной.

Также первая строка умноженная на -2 равна второй строке т.е. строки линейно зависимы, а значит определитель равен нулю и матрица является вырожденной.

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4\\
\end{pmatrix};$

а) __Решение__

Следующие преобразования матриц не приводят к изменению их ранга:

- транспонирование;

- перестановка местами двух строк (столбцов);

- умножение всех элементов строки (столбца) на число, не равное нулю;

- прибавление ко всем элементам строки (столбца) соответствующих элементов другой строки (столбца);

- выбрасывание нулевой строки (столбца);

- выбрасывание строки (столбца), являющейся линейной комбинацией других строк (столбцов).

Найдем ранг матрицы 

$$\begin{pmatrix}
1 & 2 & 3\\
1 & 1 & 1\\
2 & 3 & 4\\
\end{pmatrix}$$

Сумма первой и второй строки равна третьей, а значит третью строку можно отбросить:

$$\begin{pmatrix}
1 & 2 & 3\\
1 & 1 & 1\\
\end{pmatrix}$$

Также сумма первого и второго столбца равна третьему столбцу, а значит третий столбец можно отбросить:

$$\begin{pmatrix}
1 & 2\\
1 & 1\\
\end{pmatrix}$$

Таким образом ранг матрицы равен 2.

In [5]:
x = [1, 2, 3]
y = [1, 1, 1]
z = [2, 3, 4]

a = np.array([x, y, z])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 2


б) _Решение_

$$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}$$

Третья строка является суммой первой и второй, поэтому третью строку можно выбросить:

$$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\
2 & 3 & 5 & 6
\end{pmatrix}$$

Тким образом ранг матрицы равен 3.

In [6]:
w = [0, 0, 2, 1]
x = [0, 0, 2, 2]
y = [0, 0, 4, 3]
z = [2, 3, 5, 6]

a = np.array([w, x, y, z])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 3
