# Урок 6. Системы линейных уравнений

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
2 & 1 & -1 & 1\\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$$

Вычтем из 2-й строки первую, умноженную на 2-ю

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
0 & -1 & 1 & 5\\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$$

Вычтем из 3-й строки 1-ю

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
0 & -1 & 1 & 5\\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$$

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
-x_{2}+x_{3}+5x_{4}=-2, \\
-2x_{3}+3x_{4}=4.
\end{cases}$$

$$x_{4}=c$$

$$x_{3}=-2+3/2c$$

$$x_{2}=2+x_{3}+5x_{4}=3/2c+5c=13/2c$$

$$x_{1} = -x_{2}+x_{3}+2x_{4}=-13/2c-2+3/2c+2c=-2-3c$$

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$

In [1]:
import numpy as np

A = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
A_2 = np.array([[3, -1, 1, 4], [2, -5, -3, -17], [1, 1, -1, 0]])

rank_A = np.linalg.matrix_rank(A)
rank_A_2 = np.linalg.matrix_rank(A_2)
print(f'Ранг матрицы = {rank_A}, ранг расширенной матрицы = {rank_A_2}')

Ранг матрицы = 3, ранг расширенной матрицы = 3


 $rankA=rank \tilde A=3$, => система определена, т. е. имеет единственное решение.

   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$

In [2]:
A = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
A_2 = np.array([[2, -4, 6, 1], [1, -2, 3, -2], [3, -6, 9, 5]])

rank_A = np.linalg.matrix_rank(A)
rank_A_2 = np.linalg.matrix_rank(A_2)
print(f'Ранг матрицы = {rank_A}, ранг расширенной матрицы = {rank_A_2}')

Ранг матрицы = 1, ранг расширенной матрицы = 2


$rankA<rank \tilde A$ => система несовместна.

   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

In [3]:
A = np.array([[1, 2, 5], [3, 1, -8]])
A_2 = np.array([[1, 2, 5, 4], [3, 1, -8, -2]])

rank_A = np.linalg.matrix_rank(A)
rank_A_2 = np.linalg.matrix_rank(A_2)
print(f'Ранг матрицы = {rank_A}, ранг расширенной матрицы = {rank_A_2}')

Ранг матрицы = 2, ранг расширенной матрицы = 2


$rankA=rank \tilde A<n$ => система имеет бесконечное количество решений

__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

In [4]:
A = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
A_2 = np.array([[1, 3, -2, 4, 3], [0, 5, 0, 1, 2], [0, 0, 3, 0, 4], [0, 0, 0, 2, 1]])

rank_A = np.linalg.matrix_rank(A)
rank_A_2 = np.linalg.matrix_rank(A_2)
print(f'Ранг матрицы = {rank_A}, ранг расширенной матрицы = {rank_A_2}')

Ранг матрицы = 4, ранг расширенной матрицы = 4


$rankA=rank \tilde A=3$, => система определена, т. е. имеет единственное решение.

__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}
\Rightarrow
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b-4a\\
c
\end{matrix}
\end{pmatrix}
\Rightarrow
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & -6 & -12
\end{matrix}\right|
\begin{matrix}
a\\ 
b-4a\\
c-7a
\end{matrix}
\end{pmatrix}
\Rightarrow
$$

$$
\Rightarrow
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b-4a\\
c-7a-2b+8a
\end{matrix}
\end{pmatrix}
\Rightarrow
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b-4a\\
c+a-2b
\end{matrix}
\end{pmatrix}
$$

Чтобы ранг расширенной матрицы был больше ранга матрицы коэффициентов необходимо чтобы выполнялось неравенство: $c+a-2b\ne0$
    
$$a \ne 2b-c\\
b \ne (c+a)/2\\
c \ne 2b - a$$

# Урок 7. Системы линейных уравнений

_1._ Решить систему уравнений методом Крамера:

а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$

$\begin{pmatrix}
\left.\begin{matrix}
1 & -2\\ 
3 & -4
\end{matrix}\right|
\begin{matrix}
1\\ 
7
\end{matrix}
\end{pmatrix}$

$det\begin{pmatrix}
1 & -2\\ 
3 & -4
\end{pmatrix} = -4 + 6 = 2 \ne 0$ => система совместна

$detA_{1}=det\begin{pmatrix}
1 & -2\\ 
7 & -4
\end{pmatrix} = -4+ 14 = 10$

$detA_{2}=det\begin{pmatrix}
1 & 1\\ 
3 & 7
\end{pmatrix} = 7-3 = 4$

$x_{1}=10/2=5\\
x_{2}=4/2=2$

б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

$\begin{pmatrix}
\left.\begin{matrix}
2 & -1 & 5\\ 
1 & 1 & -3\\
2 & 4 & 1
\end{matrix}\right|
\begin{matrix}
10\\ 
-2\\
1
\end{matrix}
\end{pmatrix}$

$det\begin{pmatrix}
2 & -1 & 5\\ 
1 & 1 & -3\\
2 & 4 & 1
\end{pmatrix} = 2\begin{pmatrix}
1 & -3\\
4 & 1
\end{pmatrix}+\begin{pmatrix}
1 & -3\\
2 & 1
\end{pmatrix}+5\begin{pmatrix}
1 & 1\\
2 & 4
\end{pmatrix}=2\cdot13+7+5\cdot2=43\ne 0 $ => система совместна

$detA_{1}=det\begin{pmatrix}
10 & -1 & 5\\ 
-2 & 1 & -3\\
1 & 4 & 1
\end{pmatrix} = 10\begin{pmatrix}
1 & -3\\
4 & 1
\end{pmatrix}+\begin{pmatrix}
-2 & -3\\
1 & 1
\end{pmatrix}+5\begin{pmatrix}
-2 & 1\\
1 & 4
\end{pmatrix}=10\cdot13+1+5\cdot(-9)=86$

$detA_{2}=det\begin{pmatrix}
2 & 10 & 5\\ 
1 & -2 & -3\\
2 & 1 & 1
\end{pmatrix} = 2\begin{pmatrix}
-2 & -3\\
1 & 1
\end{pmatrix}-10\begin{pmatrix}
1 & -3\\
2 & 1
\end{pmatrix}+5\begin{pmatrix}
1 & -2\\
2 & 1
\end{pmatrix}=2\cdot1-10\cdot7+5\cdot5=-43$

$detA_{3}=det\begin{pmatrix}
2 & -1 & 10\\ 
1 & 1 & -2\\
2 & 4 & 1
\end{pmatrix} = 2\begin{pmatrix}
1 & -2\\
4 & 1
\end{pmatrix}+\begin{pmatrix}
1 & -2\\
2 & 1
\end{pmatrix}+10\begin{pmatrix}
1 & 1\\
2 & 4
\end{pmatrix}=2\cdot9+5+10\cdot2=43$

$x_{1}=86/43=2\\
x_{2}=-43/43=-1\\
x_{3}=43/43=1$

__2*.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$

_Решение_

$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}
\Rightarrow
\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
3 & 26 & 30
\end{pmatrix}
\Rightarrow
\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix}
\Rightarrow
\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix}$

$L=\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}$

   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

_Решение_

$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}
\Rightarrow
\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 15 & 23 & 6\\
4 & 22 & 53 & 33
\end{pmatrix}
\Rightarrow
\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 15 & 23 & 6\\
0 & 18 & 45 & 17
\end{pmatrix}
\Rightarrow
\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 18 & 45 & 17
\end{pmatrix}
\Rightarrow
\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 21 & 11
\end{pmatrix}
\Rightarrow
\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 0 & 4
\end{pmatrix}
$

$L=\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0\\
4 & 6 & 7 & 1
\end{pmatrix}$

__3*.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

$$ A = \begin{pmatrix}
2 & 1 & 3\\
11 & 7 & 5\\
9 & 8 & 4
\end{pmatrix}$$
$$U = \begin{pmatrix}
2 & 1 & 3\\
0 & 1.5 & -11.5\\
0 & 3.5 & -9.5\end{pmatrix} = \begin{pmatrix}
2 & 1 & 3\\
0 & 1.5 & -11.5\\
0 & 0 & \dfrac{52}{3}
\end{pmatrix}$$
$$L = \begin{pmatrix}
1 & 0 & 0 \\ 
5.5 & 1 & 0 \\ 
4.5 & \dfrac{7}{3} & 1
\end{pmatrix}$$
Решим систему $Ly=b$:$$\begin{cases}
y_1=1,\\
5.5y_1 + y_2=-6,\\
4.5y_1 + \dfrac{7}{3}y_2 + y_3=-5;
\end{cases} \Rightarrow \begin{cases}
y_1=1,\\
y_2=-11.5,\\
y_3=-9.5 + \dfrac{161}{6}=\dfrac{52}{3}
\end{cases}$$

Решим систему $Ux=y$:$$\begin{cases}
2x_1 + x_2 + 3x_3 = 1,\\
1.5x_2 - 11.5x_3 = -11.5,\\
\dfrac{52}{3}x_3 = \dfrac{52}{3};
\end{cases} \Rightarrow \begin{cases}
x_1 = -1,\\
x_2 = 0,\\
x_3 = 1.
\end{cases}$$

In [25]:
import numpy as np
import scipy.linalg

A = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
b = np.array([1, -6, -5])

lu, piv = scipy.linalg.lu_factor(A)
x = scipy.linalg.lu_solve((lu, piv), b)

print(f'A:\n{A}\n')
print(f'b:\n{b}\n')
print(f'x:\n{x.round(0)}\n')
print(f'Ax:\n{A @ x}\n')
print(f'Ax - b:\n{A @ x - b}\n')

L, U, P = scipy.linalg.lu(A)
print(f'L:\n{L.round(1)}\n')
print(f'U:\n{U.round(1)}\n')
print(f'P:\n{P.round(1)}\n')

A:
[[ 2  1  3]
 [11  7  5]
 [ 9  8  4]]

b:
[ 1 -6 -5]

x:
[-1.  0.  1.]

Ax:
[ 1. -6. -5.]

Ax - b:
[0. 0. 0.]

L:
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]

U:
[[ 1.   0.   0. ]
 [ 0.8  1.   0. ]
 [ 0.2 -0.1  1. ]]

P:
[[11.   7.   5. ]
 [ 0.   2.3 -0.1]
 [ 0.   0.   2.1]]



LU- матрицы можно вызвать из NumPy

__4*.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

Произведем разложение на $LL^{T}$:

$$l_{11}=\sqrt{a_{11}}=\sqrt{81}=9,$$$$l_{21}=\frac{a_{21}}{l_{11}}=\frac{-45}{9}=-5,$$$$l_{31}=\frac{a_{31}}{l_{11}}=\frac{45}{9}=5,$$$$l_{22}=\sqrt{a_{22}-l_{21}^{2}}=\sqrt{50 - 25}=\sqrt{25}=5,$$$$l_{32}=\frac{1}{l_{22}}(a_{32}-l_{21}l_{31})=\frac{1}{5}(-15 + 5 \cdot 5)=2,$$$$l_{33}=\sqrt{a_{33}-l_{31}^{2}-l_{32}^{2}}=\sqrt{38-25-4}=\sqrt{9}=3.$$
Получили матрицу:

$$L = \begin{pmatrix}
9 & 0 & 0 \\ 
-5 & 5 & 0 \\ 
5 & 2 & 3
\end{pmatrix}, 
L^{T} = \begin{pmatrix}
9 & -5 & 5\\
0 & 5 & 2\\
0 & 0 & 3
\end{pmatrix}.$$
Решим систему $Ly=b:$

$$\begin{cases}
9y_1 = 531,\\
-5y_1 + 5y_2 = -460,\\
5y_1 + 2y_2 + 3y_3 = 193;
\end{cases} \Rightarrow \begin{cases}
y_1 = 59,\\
y_2 = -33,\\
y_3 = -12.
\end{cases}$$
И решим систему $L^{T}x=y:$

$$\begin{cases}
9x_1 - 5x_2 + 5x_3 = 59\\
5x_2 + 2x_3 = -33,\\
3x_3 = -12;
\end{cases} \Rightarrow \begin{cases}
x_1 = 6\\
x_2 = -5,\\
x_3 = -4;
\end{cases}$$

In [26]:
import numpy as np
import scipy.linalg

A = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
b = np.array([531, -460, 193])

lu, piv = scipy.linalg.lu_factor(A)
x = scipy.linalg.lu_solve((lu, piv), b)

print(f'A:\n{A}\n')
print(f'b:\n{b}\n')
print(f'x:\n{x.round(0)}\n')
print(f'Ax:\n{A @ x}\n')
print(f'Ax - b:\n{A @ x - b}\n')

L, U, P = scipy.linalg.lu(A)
print(f'L:\n{L.round(1)}\n')
print(f'U:\n{U.round(1)}\n')
print(f'P:\n{P.round(1)}\n')

A:
[[ 81 -45  45]
 [-45  50 -15]
 [ 45 -15  38]]

b:
[ 531 -460  193]

x:
[ 6. -5. -4.]

Ax:
[ 531. -460.  193.]

Ax - b:
[0. 0. 0.]

L:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

U:
[[ 1.   0.   0. ]
 [-0.6  1.   0. ]
 [ 0.6  0.4  1. ]]

P:
[[ 81. -45.  45.]
 [  0.  25.  10.]
 [  0.   0.   9.]]



__5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.